import type { Component } from 'vue'
import {
  AddOutline,
  AppsOutline,
  ArchiveOutline,
  ArrowBackOutline,
  ArrowUpOutline,
  BookmarkOutline,
  BookOutline,
  CalendarOutline,
  ChatboxOutline,
  ChatbubblesOutline,
  CheckmarkCircle,
  ChevronDownOutline,
  ChevronUpOutline,
  ArrowDownCircleOutline,
  ChevronForwardOutline,
  CloseOutline,
  ContractOutline,
  CopyOutline,
  DocumentTextOutline,
  EllipsisHorizontal,
  EyeOutline,
  CreateOutline,
  ExpandOutline,
  EyeOffOutline,
  FlashOutline,
  FlameOutline,
  FolderOpenOutline,
  FolderOutline,
  GitNetworkOutline,
  GlobeOutline,
  Heart,
  HeartOutline,
  HomeOutline,
  InformationCircleOutline,
  ImageOutline,
  LayersOutline,
  LinkOutline,
  LogoGithub,
  LockClosedOutline,
  LogInOutline,
  LogOutOutline,
  MailOutline,
  MegaphoneOutline,
  MenuOutline,
  MoonOutline,
  NotificationsOutline,
  OpenOutline,
  PaperPlaneOutline,
  PencilOutline,
  PeopleOutline,
  PersonOutline,
  PersonCircleOutline,
  PricetagOutline,
  SearchOutline,
  ShieldCheckmarkOutline,
  SparklesOutline,
  StarOutline,
  SunnyOutline,
  TrendingDownOutline,
  TrendingUpOutline,
  TrashOutline
} from '@vicons/ionicons5'

export const appIcons = {
  verified: CheckmarkCircle,
  github: LogoGithub,
  gitee: GitNetworkOutline,
  qq: ChatbubblesOutline,
  email: MailOutline,
  weibo: MegaphoneOutline,
  zhihu: BookOutline,
  collect: BookmarkOutline,
  search: SearchOutline,
  themeLight: SunnyOutline,
  themeDark: MoonOutline,
  create: CreateOutline,
  user: PersonCircleOutline,
  menu: MenuOutline,
  home: HomeOutline,
  archive: ArchiveOutline,
  category: FolderOpenOutline,
  folder: FolderOutline,
  folderOpen: FolderOpenOutline,
  tag: PricetagOutline,
  navigation: GlobeOutline,
  links: LinkOutline,
  about: InformationCircleOutline,
  login: LogInOutline,
  logout: LogOutOutline,
  sparkles: SparklesOutline,
  add: AddOutline,
  back: ArrowBackOutline,
  backTop: ArrowUpOutline,
  arrowForward: ChevronForwardOutline,
  comment: ChatboxOutline,
  person: PersonOutline,
  password: LockClosedOutline,
  captcha: ShieldCheckmarkOutline,
  brand: LayersOutline,
  eye: EyeOutline,
  eyeOff: EyeOffOutline,
  fullscreenEnter: ExpandOutline,
  fullscreenExit: ContractOutline,
  document: DocumentTextOutline,
  runtime: FlashOutline,
  visitors: PeopleOutline,
  notice: NotificationsOutline,
  close: CloseOutline,
  mail: MailOutline,
  send: PaperPlaneOutline,
  information: InformationCircleOutline,
  image: ImageOutline,
  calendar: CalendarOutline,
  external: OpenOutline,
  star: StarOutline,
  /** 空心心形（Ionicons 5 Outline） */
  heart: HeartOutline,
  /** 实心心形（Ionicons 5 Filled），用于已点赞等状态 */
  heartFilled: Heart,
  flame: FlameOutline,
  grid: AppsOutline,
  trendUp: TrendingUpOutline,
  trendDown: TrendingDownOutline,
  trash: TrashOutline,
  chevronDown: ChevronDownOutline,
  chevronUp: ChevronUpOutline,
  arrowDown: ArrowDownCircleOutline,
  edit: PencilOutline,
  copy: CopyOutline,
  moreHorizontal: EllipsisHorizontal
} as const satisfies Record<string, Component>

export type AppIconName = keyof typeof appIcons

